# Site settings
title: "Linux as everyday develop station"
email: "chrono.dark@gmail.com"
description: "Scripts,Apps,Alternatives,Tutorials and how to's on making Linux the default OS for develop awesome apps"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.io/cortiz/0x29A" # the base hostname & protocol for your site
twitter_username: ""
github_username: "cortiz"
# Build settings
markdown: rouge
